import os

AWS_DEFAULT_REGION = "X-Y-Z"
JWT_TOKEN_LOCATION = ["cookies"]
JWT_COOKIE_SECURE = True

JWT_COOKIE_CSRF_PROTECT = False
JWT_ALGORITHM = "RS256"
JWT_IDENTITY_CLAIM = "sub"

SECRET_KEY = "YOUR_SECRET_KEY"
JWT_PRIVATE_KEY = "JWT_PRIVATE_KEY"
JWT_SECRET_KEY = "JWT_SECRET_KEY"
AWS_COGNITO_DOMAIN = "https://YOUR_COGNITO_SUBDOMAIN.auth.OUR_REGION.amazoncognito.com"
AWS_COGNITO_USER_POOL_ID = "COGNITO_POOL_ID"
AWS_COGNITO_USER_POOL_CLIENT_ID = 'CLIENT_ID'
AWS_COGNITO_USER_POOL_CLIENT_SECRET = "USER_POOL_CLIENT_SECRET"
AWS_COGNITO_REDIRECT_URL = 'http://localhost:5000/loggedin'